### ISSUE TITLE
[0422] FeedManager createReply 메소드 문제 2건

### ISSUE THREAD

**Issue by jdjin3000** [DongjunLim/onion-BackEnd#12]
1. 댓글 리스트에 $push 시, 고유 _id가 생성되지 않는 문제
2. create_at -> Date.now() 가 적용되지 않음.

-> Reply 스키마를 생성하여 추가하는 것으로 해결되는지 테스트 할 것.

**Comment by DongjunLim** [comment]
mongoose에서 subDocument를 사용하여 해결
