### ISSUE TITLE
[0423] 클라이언트 -> 서버 전송 시 오류 2건

### ISSUE THREAD

**Issue by jdjin3000** [DongjunLim/onion-BackEnd#13]
1. PayloadTooLargeError: request entity too large
2. PayloadTooLargeError: too many parameters

**Comment by jdjin3000** [comment]
1.
코드 상에
app.use(bodyParser.json({limit:"50MB"}));
app.use(bodyParser.urlencoded({limit:"50MB", extended: true}));
추가 시 해결.

2.
코드 상에
bodyParser.urlencoded 옵션으로 {parameterLimit: 1000000} 추가.
(
app.use(bodyParser.urlencoded({limit:"50MB", extended: true, parameterLimit: 1000000}));
)

**Comment by DongjunLim** [comment]
### 방법변경.
사진파일은 Content type을 multipart 를 사용하여 별도로 request 하는 형식으로 구조 변경하여 해결

### body-parsing 에러
서버문제가 아니라 테스트 코드 문제로 확인. 테스트 코드 수정하여 해결
