### ISSUE TITLE
분류기 성능향상을 위한 학습개선

### ISSUE THREAD

**Issue by DongjunLim** [DongjunLim/onion-BackEnd#22]
남성상의 학습 시나리오
- 전처리 X, 배경, 인물 크롭 X
- 데이터 리사이징 기존보다 크게( 비율 1.5배? )

남성하의 학습 시나리오
- 입력데이터 rgb에서 hsv로 변환
- 데이터 리사이징 기존보다 크게( 비율 1.5배? )

컬러 학습 시나리오
- 사전학습 취소
- 입력 데이터 rgb에서 hsv로 변환

**Comment by jdjin3000** [comment]
현재 진행한 시나리오
<남성상의>
- 인물 크롭 O, 배경 제거 O

<색상>
- 인물 크롭 O, 배경 제거 O
