### ISSUE TITLE
[0420] 백엔드 논의사항

### ISSUE THREAD

**Issue by jdjin3000** [DongjunLim/onion-BackEnd#5]
논의사항
- DB설계 시의 모든 idx를 MongoDB 다큐먼트에서 제공하는 _id로 변경
- FeedManager 메소드에서 ...
createReply vs createFeed 게시자 아이디를 받아야하는가? 토큰을 써서 사용해야 하는가?
(관련 메소드 : createReply, createFeed, getTimelineFeedList, getUserFeedList)

**Comment by DongjunLim** [comment]
1. mongoDB에서 제공하는 _id 컬럼을 인덱스로 함
2. 클라이언트가 직접 작성할때 넘기는 사용자 파라미터는 무조건 토큰으로 통일(게시글 작성, 댓글 작성 등)
