### ISSUE TITLE
[0421] like 메소드 책임소재 문제 외

### ISSUE THREAD

**Issue by DongjunLim** [DongjunLim/onion-BackEnd#7]
### like method 책임소재
게시물에 좋아요를 추가하는 like method를
FeedManager가 가지고 있어야 할지,
UserManager가 가지고 있어야 할지 정해야 함.

Like 기능을 수행하면 user 컬렉션과 Feed 컬렉션 내부 데이터가 수정되므로
어느쪽에 있어도 말이 되긴함

### UserManager 메소드 입력 파라미터 누락
추가로 클래스 명세서에 like, deletelike 메소드에 입력 파라미터가 feedId밖에 없음.
좋아요 기능을 수행하려면 입력 파라미터로 userNickname도 필요.

다시보니 좋아요 기능말고 북마크, 상품구매, 버킷리스트에 대해서도 입력 파라미터로 userNickname이 없음
설계서에 입력 파라미터로 추가하고, 코드에도 반영해야 할듯

### 북마크, 장바구니 목록 조회 기능 누락
userManager 메소드에 북마크 피드 썸네일과 장바구니를 담은 상품목록 조회 메소드가 누락되어 있음.
확인 후 추가해야 할듯

**Comment by jdjin3000** [comment]
1.like method 책임소재
일단 UserManager가 가지고 있기로 (나중에 문제시, 메소드 채로 옮기면 해결 가능)

2. UserManager 메소드 입력 파라미터 누락
Controller 단에서 토큰으로부터 userNickname 추출 후, Manager 단으로 파라미터 형식으로 건네주는 방식으로 고정. -> Manager 클래스 메소드에 userNickname 추가해야

3.북마크, 장바구니 목록 조회 기능 누락
userManager 메소드에 북마크 피드 썸네일과 장바구니를 담은 상품목록 조회 메소드 추가 예정.
